name: medwear
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0

  # Icons
  cupertino_icons: ^1.0.8

  # Base de datos local SQLite
  floor: ^1.5.0
  sqflite: ^2.3.0

  # Notificaciones locales
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Gestión de estado
  get: ^4.6.6

  # Utilidades
  intl: ^0.19.0
  
  # Wear OS (Google Play Services)
  http: ^1.1.0
  
  # Comunicación Data Layer
  google_maps_flutter: ^2.5.0  # opcional si necesitas maps
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Floor code generator
  floor_generator: ^1.5.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
